name: Version Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Release Notes
        run: sed '1p;1,/^##/!d;/##/d' CHANGELOG.md > ${{ github.ref_name }}.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.ref_name }}.md
        env:
          GITHUB_REPOSITORY: Argyle-Software/dilithium