name: WebAssembly Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install wasm-pack
      run: |
        rustup target add wasm32-unknown-unknown
        cargo install wasm-pack
        wasm-pack build --target nodejs

    - name: Test webassembly
      working-directory: ./tests
      run: ./wasm.js
        
